//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ENIMS.Common {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ENIMS.Common.Localization.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account is inactive.
        /// </summary>
        public static string AccountIsInactive {
            get {
                return ResourceManager.GetString("AccountIsInactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address1.
        /// </summary>
        public static string Address1 {
            get {
                return ResourceManager.GetString("Address1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address2.
        /// </summary>
        public static string Address2 {
            get {
                return ResourceManager.GetString("Address2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AllowedOnlyForSelfUpdate.
        /// </summary>
        public static string AllowedOnlyForSelfUpdate {
            get {
                return ResourceManager.GetString("AllowedOnlyForSelfUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already Active!.
        /// </summary>
        public static string AlreadyActiveRecord {
            get {
                return ResourceManager.GetString("AlreadyActiveRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already In-Active!!.
        /// </summary>
        public static string AlreadyInActiveRecord {
            get {
                return ResourceManager.GetString("AlreadyInActiveRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atleast you must add two item item to the composit line item.
        /// </summary>
        public static string AtleastAddTwoLineItem {
            get {
                return ResourceManager.GetString("AtleastAddTwoLineItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atleast one Good item must be included in the composit item.
        /// </summary>
        public static string AtleastOneItemMustBeGoodType {
            get {
                return ResourceManager.GetString("AtleastOneItemMustBeGoodType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atleast one item must exist in a group.
        /// </summary>
        public static string AtleastOneItemMustExistInAgroup {
            get {
                return ResourceManager.GetString("AtleastOneItemMustExistInAgroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atleast select one privilage.
        /// </summary>
        public static string AtleastSelectOnePrivilage {
            get {
                return ResourceManager.GetString("AtleastSelectOnePrivilage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bad Request.
        /// </summary>
        public static string BadRequest {
            get {
                return ResourceManager.GetString("BadRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bundle already deleted.
        /// </summary>
        public static string BundleAlreadyDeleted {
            get {
                return ResourceManager.GetString("BundleAlreadyDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bundle information does not exist.
        /// </summary>
        public static string BundleInfoDoesNotExist {
            get {
                return ResourceManager.GetString("BundleInfoDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bundling is allowed for composit item only.
        /// </summary>
        public static string BundlingIsAllowedOnlyForCompositItem {
            get {
                return ResourceManager.GetString("BundlingIsAllowedOnlyForCompositItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business error occured while processing your request.
        /// </summary>
        public static string BusinessErrorWhileProcessingYourRequest {
            get {
                return ResourceManager.GetString("BusinessErrorWhileProcessingYourRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can not add same from and to sector.
        /// </summary>
        public static string CanNotAddSameFromToSector {
            get {
                return ResourceManager.GetString("CanNotAddSameFromToSector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can not update your own status or role.
        /// </summary>
        public static string CanNotUpdateOwnStatusOrRole {
            get {
                return ResourceManager.GetString("CanNotUpdateOwnStatusOrRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not Update Or Delete Pre Defined User!.
        /// </summary>
        public static string CantUpdateOrDeletePreDefinedUser {
            get {
                return ResourceManager.GetString("CantUpdateOrDeletePreDefinedUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot change your own status or role..
        /// </summary>
        public static string CantUpdateOwnStatusOrRole {
            get {
                return ResourceManager.GetString("CantUpdateOwnStatusOrRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client Id.
        /// </summary>
        public static string ClientId {
            get {
                return ResourceManager.GetString("ClientId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company name already exist.
        /// </summary>
        public static string CompanyAlreadyExist {
            get {
                return ResourceManager.GetString("CompanyAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Composit item name already exist.
        /// </summary>
        public static string CompositItemAlreadyExist {
            get {
                return ResourceManager.GetString("CompositItemAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Composit item does not exist.
        /// </summary>
        public static string CompositItemDoesNotExist {
            get {
                return ResourceManager.GetString("CompositItemDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation Email Send Successfully.
        /// </summary>
        public static string ConfirmationEmailSendMessage {
            get {
                return ResourceManager.GetString("ConfirmationEmailSendMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country Code.
        /// </summary>
        public static string CountryCode {
            get {
                return ResourceManager.GetString("CountryCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CountryName.
        /// </summary>
        public static string CountryName {
            get {
                return ResourceManager.GetString("CountryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CountryPhoneCode.
        /// </summary>
        public static string CountryPhoneCode {
            get {
                return ResourceManager.GetString("CountryPhoneCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency Code.
        /// </summary>
        public static string CurrencyCode {
            get {
                return ResourceManager.GetString("CurrencyCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency Format.
        /// </summary>
        public static string CurrencyFormat {
            get {
                return ResourceManager.GetString("CurrencyFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency Name.
        /// </summary>
        public static string CurrencyName {
            get {
                return ResourceManager.GetString("CurrencyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency Not Found!!.
        /// </summary>
        public static string CurrencyNotFound {
            get {
                return ResourceManager.GetString("CurrencyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency Symbol.
        /// </summary>
        public static string CurrencySymbol {
            get {
                return ResourceManager.GetString("CurrencySymbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Username.
        /// </summary>
        public static string CurrentUserName {
            get {
                return ResourceManager.GetString("CurrentUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database operation has failed, please try again.
        /// </summary>
        public static string DatabaseOperationFailed {
            get {
                return ResourceManager.GetString("DatabaseOperationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Organization Not Created.
        /// </summary>
        public static string DefaultOrganizationNotCreated {
            get {
                return ResourceManager.GetString("DefaultOrganizationNotCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default warehouse is not created for the current organization.
        /// </summary>
        public static string DefaultWarehouseIsNotCreated {
            get {
                return ResourceManager.GetString("DefaultWarehouseIsNotCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Effective Date.
        /// </summary>
        public static string EffectiveDate {
            get {
                return ResourceManager.GetString("EffectiveDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email already confirmed.
        /// </summary>
        public static string EmailAlreadyConfirmed {
            get {
                return ResourceManager.GetString("EmailAlreadyConfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User email already exist.
        /// </summary>
        public static string EmailAlreadyExist {
            get {
                return ResourceManager.GetString("EmailAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End date.
        /// </summary>
        public static string EndDate {
            get {
                return ResourceManager.GetString("EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error has occured while processing your request, please try again.
        /// </summary>
        public static string ErrorHasOccuredWhileProcessingYourRequest {
            get {
                return ResourceManager.GetString("ErrorHasOccuredWhileProcessingYourRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exchange Rate.
        /// </summary>
        public static string ExchangeRate {
            get {
                return ResourceManager.GetString("ExchangeRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Upload Error.
        /// </summary>
        public static string FileUploadError {
            get {
                return ResourceManager.GetString("FileUploadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found Tax That Doesnt Exist Or Invalid.
        /// </summary>
        public static string FoundTaxThatDoesntExistOrInvalid {
            get {
                return ResourceManager.GetString("FoundTaxThatDoesntExistOrInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal Server Error from the custom Exception..
        /// </summary>
        public static string InternalServerError {
            get {
                return ResourceManager.GetString("InternalServerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid client credential, please try again..
        /// </summary>
        public static string InvalidClientCredential {
            get {
                return ResourceManager.GetString("InvalidClientCredential", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid confirmation token.
        /// </summary>
        public static string InvalidConfirmationToken {
            get {
                return ResourceManager.GetString("InvalidConfirmationToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Item Transaction.
        /// </summary>
        public static string InvalidItemTransactionId {
            get {
                return ResourceManager.GetString("InvalidItemTransactionId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InvalidPasswordHasherCompatibilityMode.
        /// </summary>
        public static string InvalidPasswordHasherCompatibilityMode {
            get {
                return ResourceManager.GetString("InvalidPasswordHasherCompatibilityMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InvalidPasswordHasherIterationCount.
        /// </summary>
        public static string InvalidPasswordHasherIterationCount {
            get {
                return ResourceManager.GetString("InvalidPasswordHasherIterationCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid password recovery token.
        /// </summary>
        public static string InvalidPasswordRecoveryToken {
            get {
                return ResourceManager.GetString("InvalidPasswordRecoveryToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid refresh token, please try to login again with your client id and secrate key.
        /// </summary>
        public static string InvalidRefreshToken {
            get {
                return ResourceManager.GetString("InvalidRefreshToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid user login crednetial.
        /// </summary>
        public static string InvalidUserCredential {
            get {
                return ResourceManager.GetString("InvalidUserCredential", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid username or password.
        /// </summary>
        public static string InvalidUsernameOrPassword {
            get {
                return ResourceManager.GetString("InvalidUsernameOrPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invitation Email Send Succesfully.
        /// </summary>
        public static string InviteEmailSendMessage {
            get {
                return ResourceManager.GetString("InviteEmailSendMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Base Currency.
        /// </summary>
        public static string IsBaseCurrency {
            get {
                return ResourceManager.GetString("IsBaseCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Default Warehouse?.
        /// </summary>
        public static string IsDefaultWarehouse {
            get {
                return ResourceManager.GetString("IsDefaultWarehouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is record protected for edit?.
        /// </summary>
        public static string IsRecordProtectedForEdit {
            get {
                return ResourceManager.GetString("IsRecordProtectedForEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item already exist.
        /// </summary>
        public static string ItemAlreadyExist {
            get {
                return ResourceManager.GetString("ItemAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item attribute option does not exist {0}.
        /// </summary>
        public static string ItemAttributeOptionDoesNotExist {
            get {
                return ResourceManager.GetString("ItemAttributeOptionDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item {0} does not belong to the current group {1}.
        /// </summary>
        public static string ItemDoesNotBelongToTheCurrentGroup {
            get {
                return ResourceManager.GetString("ItemDoesNotBelongToTheCurrentGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item does not exist.
        /// </summary>
        public static string ItemDoesNotExist {
            get {
                return ResourceManager.GetString("ItemDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item group already exist.
        /// </summary>
        public static string ItemGroupAlreadyExist {
            get {
                return ResourceManager.GetString("ItemGroupAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item group does not exist.
        /// </summary>
        public static string ItemGroupDoesNotExist {
            get {
                return ResourceManager.GetString("ItemGroupDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item group has sucessfully deleted.
        /// </summary>
        public static string ItemGroupHasSucessfullyDeleted {
            get {
                return ResourceManager.GetString("ItemGroupHasSucessfullyDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item group sucessfully created.
        /// </summary>
        public static string ItemGroupSucessfullyCreated {
            get {
                return ResourceManager.GetString("ItemGroupSucessfullyCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item has sucessfully deledted.
        /// </summary>
        public static string ItemHasSucessfullyDeleted {
            get {
                return ResourceManager.GetString("ItemHasSucessfullyDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item name {0} must be unique.
        /// </summary>
        public static string ItemNameMustBeUnique {
            get {
                return ResourceManager.GetString("ItemNameMustBeUnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item sucessfully created.
        /// </summary>
        public static string ItemSucessfullyCreated {
            get {
                return ResourceManager.GetString("ItemSucessfullyCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item id {0} does not exist.
        /// </summary>
        public static string ItemWithIdDoesNotExist {
            get {
                return ResourceManager.GetString("ItemWithIdDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item with name {0} does not exist.
        /// </summary>
        public static string ItemWithNameDoesNotExist {
            get {
                return ResourceManager.GetString("ItemWithNameDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item with same name {0} already exist.
        /// </summary>
        public static string ItemWithTheSameNameAlreadyExist {
            get {
                return ResourceManager.GetString("ItemWithTheSameNameAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changed on.
        /// </summary>
        public static string LastUpdateDate {
            get {
                return ResourceManager.GetString("LastUpdateDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model Error.
        /// </summary>
        public static string ModelError {
            get {
                return ResourceManager.GetString("ModelError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Organization found with this search.
        /// </summary>
        public static string NoOrganizationFoundWithThisSearch {
            get {
                return ResourceManager.GetString("NoOrganizationFoundWithThisSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Role Organization Correlation Selected.
        /// </summary>
        public static string NoRoleOrganizationCorrelationSelected {
            get {
                return ResourceManager.GetString("NoRoleOrganizationCorrelationSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Allowed!!.
        /// </summary>
        public static string NotAllowed {
            get {
                return ResourceManager.GetString("NotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Allowed It Is A GroupTax!!.
        /// </summary>
        public static string NotAllowedItIsAGroupTax {
            get {
                return ResourceManager.GetString("NotAllowedItIsAGroupTax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Allowed It Is Not A Group Tax.
        /// </summary>
        public static string NotAllowedItIsNotAGroupTax {
            get {
                return ResourceManager.GetString("NotAllowedItIsNotAGroupTax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Warehouse found with this search.
        /// </summary>
        public static string NoWarehouseFoundWithThisSearch {
            get {
                return ResourceManager.GetString("NoWarehouseFoundWithThisSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NoWarehouseRoleCorrelationSelected.
        /// </summary>
        public static string NoWarehouseRoleCorrelationSelected {
            get {
                return ResourceManager.GetString("NoWarehouseRoleCorrelationSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only one service type can be added in to a composit item.
        /// </summary>
        public static string OnlyOneServiceTypeCanBeAddedInToCompositItem {
            get {
                return ResourceManager.GetString("OnlyOneServiceTypeCanBeAddedInToCompositItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to operation ended with errors.
        /// </summary>
        public static string OperationEndWithError {
            get {
                return ResourceManager.GetString("OperationEndWithError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation sucessfully completed.
        /// </summary>
        public static string OperationSucessfullyCompleted {
            get {
                return ResourceManager.GetString("OperationSucessfullyCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation sucessfully completed {0} number of record(s) affected.
        /// </summary>
        public static string OperationSucessfullyCompletedNumberOfRecordAffected {
            get {
                return ResourceManager.GetString("OperationSucessfullyCompletedNumberOfRecordAffected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password has been changed successfully..
        /// </summary>
        public static string PasswordSucessfullyChanged {
            get {
                return ResourceManager.GetString("PasswordSucessfullyChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone no..
        /// </summary>
        public static string PhoneNo {
            get {
                return ResourceManager.GetString("PhoneNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check stock balance for item with batch {0}.
        /// </summary>
        public static string PleaseCheckStockBalanceForBatch {
            get {
                return ResourceManager.GetString("PleaseCheckStockBalanceForBatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check stock balance for item with serial number {0}.
        /// </summary>
        public static string PleaseCheckStockBalanceForSerialNumber {
            get {
                return ResourceManager.GetString("PleaseCheckStockBalanceForSerialNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select at least one role.
        /// </summary>
        public static string PleaseSelectAtLeastOneRole {
            get {
                return ResourceManager.GetString("PleaseSelectAtLeastOneRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select one record to Delete.
        /// </summary>
        public static string PleaseSelectOneRecordToDelete {
            get {
                return ResourceManager.GetString("PleaseSelectOneRecordToDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select at least one record to update.
        /// </summary>
        public static string PleaseSelectOneRecordToUpdate {
            get {
                return ResourceManager.GetString("PleaseSelectOneRecordToUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select Valid Currency.
        /// </summary>
        public static string PleaseSelectValidCurrency {
            get {
                return ResourceManager.GetString("PleaseSelectValidCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price Precision.
        /// </summary>
        public static string PricePrecision {
            get {
                return ResourceManager.GetString("PricePrecision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primary Can not Be Deleted!!.
        /// </summary>
        public static string PrimaryCantBeDeleted {
            get {
                return ResourceManager.GetString("PrimaryCantBeDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primary Cannot be In-Active.
        /// </summary>
        public static string PrimaryCantBeInActive {
            get {
                return ResourceManager.GetString("PrimaryCantBeInActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primary Contact Can not Be Found!!.
        /// </summary>
        public static string PrimaryContactCantBeFound {
            get {
                return ResourceManager.GetString("PrimaryContactCantBeFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The same record already exist, please try again.
        /// </summary>
        public static string RecordAlreadyExist {
            get {
                return ResourceManager.GetString("RecordAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created by.
        /// </summary>
        public static string RecordCreatedBy {
            get {
                return ResourceManager.GetString("RecordCreatedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created date.
        /// </summary>
        public static string RecordCreatedDate {
            get {
                return ResourceManager.GetString("RecordCreatedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record does not exist in the database.
        /// </summary>
        public static string RecordDoesNotExist {
            get {
                return ResourceManager.GetString("RecordDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record status.
        /// </summary>
        public static string RecordStatus {
            get {
                return ResourceManager.GetString("RecordStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record scuessfully created.
        /// </summary>
        public static string RecordSucessfullyCreated {
            get {
                return ResourceManager.GetString("RecordSucessfullyCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record sucessfully updated.
        /// </summary>
        public static string RecordSucessfullyUpdated {
            get {
                return ResourceManager.GetString("RecordSucessfullyUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update date.
        /// </summary>
        public static string RecordUpdateDate {
            get {
                return ResourceManager.GetString("RecordUpdateDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated by.
        /// </summary>
        public static string RecordUpdatedBy {
            get {
                return ResourceManager.GetString("RecordUpdatedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remark Is Mandatory.
        /// </summary>
        public static string RemarkIsMandatory {
            get {
                return ResourceManager.GetString("RemarkIsMandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The request couldn&apos;t be processed.
        /// </summary>
        public static string RequestCouldntBeProcessed {
            get {
                return ResourceManager.GetString("RequestCouldntBeProcessed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, predefined roles cannot be edited or deleted. Clone the role instead..
        /// </summary>
        public static string RoleCantBeEditedOrDeleted {
            get {
                return ResourceManager.GetString("RoleCantBeEditedOrDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, you could not delete this role as it is assigned to user..
        /// </summary>
        public static string RoleDeleteNotAllowedMessage {
            get {
                return ResourceManager.GetString("RoleDeleteNotAllowedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role Does not Exist in the system.
        /// </summary>
        public static string RoleDoesntExist {
            get {
                return ResourceManager.GetString("RoleDoesntExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role Not Selected.
        /// </summary>
        public static string RoleNotSelected {
            get {
                return ResourceManager.GetString("RoleNotSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Same Date Exchange Rate Is Already Exist You Can Edit Instead!.
        /// </summary>
        public static string SameDateExchangeRateIsAlreadyExistYouCanEdit {
            get {
                return ResourceManager.GetString("SameDateExchangeRateIsAlreadyExistYouCanEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Same Date Exchange Rate Is Already Exist You Can Add Instead!!.
        /// </summary>
        public static string SameDateExchangeRateIsAlreadyExistYouCanEditAdd {
            get {
                return ResourceManager.GetString("SameDateExchangeRateIsAlreadyExistYouCanEditAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secrate key.
        /// </summary>
        public static string SecrateKey {
            get {
                return ResourceManager.GetString("SecrateKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select Client.
        /// </summary>
        public static string SelectClient {
            get {
                return ResourceManager.GetString("SelectClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SKU Number alrady exist.
        /// </summary>
        public static string SKUAlreadyExist {
            get {
                return ResourceManager.GetString("SKUAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SKU {0} must be unique.
        /// </summary>
        public static string SKUMustBeUnique {
            get {
                return ResourceManager.GetString("SKUMustBeUnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start date.
        /// </summary>
        public static string StartDate {
            get {
                return ResourceManager.GetString("StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start date must be less than from end date.
        /// </summary>
        public static string StartDateMustBeLessThanFromEndDate {
            get {
                return ResourceManager.GetString("StartDateMustBeLessThanFromEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        public static string State {
            get {
                return ResourceManager.GetString("State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account subscription information does not exist.
        /// </summary>
        public static string SubscriptionInfoDoesNotExist {
            get {
                return ResourceManager.GetString("SubscriptionInfoDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SubscriptionNotFound.
        /// </summary>
        public static string SubscriptionNotFound {
            get {
                return ResourceManager.GetString("SubscriptionNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sucessfully logged in.
        /// </summary>
        public static string SucessfullyLogedIn {
            get {
                return ResourceManager.GetString("SucessfullyLogedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The same SKU {0} already exist.
        /// </summary>
        public static string TheSameSKUAlreadyExist {
            get {
                return ResourceManager.GetString("TheSameSKUAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to this item type can not be used for creating composit item.
        /// </summary>
        public static string ThisItemCanNotBeUsedForCreatingCompositItem {
            get {
                return ResourceManager.GetString("ThisItemCanNotBeUsedForCreatingCompositItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This tax is associated with the tax group(s). Hence, it cannot be deleted..
        /// </summary>
        public static string ThistaxisassociatedwiththetaxgroupHenceitcannotbedeleted {
            get {
                return ResourceManager.GetString("ThistaxisassociatedwiththetaxgroupHenceitcannotbedeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title Name.
        /// </summary>
        public static string TitleName {
            get {
                return ResourceManager.GetString("TitleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction Is Not On The Same Subscription.
        /// </summary>
        public static string TransactionIsNotOnTheSameSubscription {
            get {
                return ResourceManager.GetString("TransactionIsNotOnTheSameSubscription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TransationAlreadyExist.
        /// </summary>
        public static string TransationAlreadyExist {
            get {
                return ResourceManager.GetString("TransationAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid credential, please try again.
        /// </summary>
        public static string UnableToLoginInvalidUserNameOrPassword {
            get {
                return ResourceManager.GetString("UnableToLoginInvalidUserNameOrPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anauthorized access.
        /// </summary>
        public static string UnauthorizedAccess {
            get {
                return ResourceManager.GetString("UnauthorizedAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unautorized access.
        /// </summary>
        public static string UnautorizedAccess {
            get {
                return ResourceManager.GetString("UnautorizedAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UnitOfMeasurementName.
        /// </summary>
        public static string UnitOfMeasurementName {
            get {
                return ResourceManager.GetString("UnitOfMeasurementName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changed by.
        /// </summary>
        public static string UpdatedBy {
            get {
                return ResourceManager.GetString("UpdatedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Account Already Exist!!.
        /// </summary>
        public static string UserAccountAlreadyExist {
            get {
                return ResourceManager.GetString("UserAccountAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User account does not exist.
        /// </summary>
        public static string UserAccountDoesNotExist {
            get {
                return ResourceManager.GetString("UserAccountDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User account is locked.
        /// </summary>
        public static string UserAccountIsLocked {
            get {
                return ResourceManager.GetString("UserAccountIsLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User is Already Active.
        /// </summary>
        public static string UserAlreadyActiveMessage {
            get {
                return ResourceManager.GetString("UserAlreadyActiveMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User already logged out.
        /// </summary>
        public static string UserAlreadyLoggedOut {
            get {
                return ResourceManager.GetString("UserAlreadyLoggedOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Can not Be Activated!!.
        /// </summary>
        public static string UserCantBeActivated {
            get {
                return ResourceManager.GetString("UserCantBeActivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Can&apos;t Login.
        /// </summary>
        public static string UserCantLogin {
            get {
                return ResourceManager.GetString("UserCantLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authorized user.
        /// </summary>
        public static string UserIsAuthorized {
            get {
                return ResourceManager.GetString("UserIsAuthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Is Deleted.
        /// </summary>
        public static string UserIsDeletedMessage {
            get {
                return ResourceManager.GetString("UserIsDeletedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User is already InActive.
        /// </summary>
        public static string UserIsInActiveAlreadyMessge {
            get {
                return ResourceManager.GetString("UserIsInActiveAlreadyMessge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Not Logged In.
        /// </summary>
        public static string UserNotLoggedIn {
            get {
                return ResourceManager.GetString("UserNotLoggedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have sucessfully logged in.
        /// </summary>
        public static string UserSucessfullyLoggedIn {
            get {
                return ResourceManager.GetString("UserSucessfullyLoggedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input validation failed, please try again with valid input.
        /// </summary>
        public static string ValidationFailed {
            get {
                return ResourceManager.GetString("ValidationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warehouse name.
        /// </summary>
        public static string WarehouseName {
            get {
                return ResourceManager.GetString("WarehouseName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can&apos;t delete bundle for which transaction is already made for composit item with serial/batch number tracking.
        /// </summary>
        public static string YouCanNotDeleteBundleWithBatchSerialNumberIsEnabledForWhichTransactionIsMade {
            get {
                return ResourceManager.GetString("YouCanNotDeleteBundleWithBatchSerialNumberIsEnabledForWhichTransactionIsMade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot have more than one compound tax in a tax group.
        /// </summary>
        public static string Youcannothavemorethanonecompoundtaxinataxgroup {
            get {
                return ResourceManager.GetString("Youcannothavemorethanonecompoundtaxinataxgroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have enough stock in hand for bundling item {0} Please re-stock and try again..
        /// </summary>
        public static string YouDoNotHaveEnoughStockOnHandForBundlingItem {
            get {
                return ResourceManager.GetString("YouDoNotHaveEnoughStockOnHandForBundlingItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your email address is sucessfully confirmed.
        /// </summary>
        public static string YourEmailAddressIsSucessfullyConfirmed {
            get {
                return ResourceManager.GetString("YourEmailAddressIsSucessfullyConfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zip code.
        /// </summary>
        public static string ZipCode {
            get {
                return ResourceManager.GetString("ZipCode", resourceCulture);
            }
        }
    }
}
